### ISSUE TITLE
project-plan.md

### ISSUE THREAD

**Issue by Ajaz64053** [jvalue/made-template#35]
## User Story
1. As a {user/persona}
2. I want {to perform this action}
3. So that {I can accomplish this goal}

## User Acceptance Criteria
- [ ] {acceptance criteria 1}

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing
- [ ] Documentation is updated/extended

**Comment by rhazn** [comment]
Hi @Ajaz64053 , please create your issues in your repository and not the template one. Thank you.

**Comment by Ajaz64053** [comment]
Hlo @rhzan I completed the project work 2 but I am not sure that I done correctly . So can you please look out it and tell me if I have to make any changes.
Thank you

**Comment by rhazn** [comment]
Please post your questions in the StudOn forum, not here.
