### ISSUE TITLE
[FEATURE] Extract the data from the two data sources

### ISSUE THREAD

**Issue by Zylesto** [jvalue/made-template#39]
## User Story
1. As a data scientist
2. I want to extract data from the World Bank and FAOSTAT
3. So that I can analyze the correlation between food prices and temperature change.

## User Acceptance Criteria
- [ ] The data is extracted accurately.

## Definition of Done
- [ ] Code for the data extraction has been written
- [ ] Data extraction is verified

**Comment by rhazn** [comment]
You'll need to create issues on your own repository, not the template one please.

**Comment by Zylesto** [comment]
Sorry, I havent seen it :(
