### ISSUE TITLE
[FEATURE] Explore the data

### ISSUE THREAD

**Issue by Zylesto** [jvalue/made-template#40]
## User Story
1. As a data analyst
2. I want to explore the dataset
3. So that I can understand the data's structure, quality, and identify any anomalies.

## User Acceptance Criteria
- [ ] Preliminary analysis of the dataset is complete.
- [ ] Data quality issues are documented.

## Notes
- Take note of missing values and outliers.

## Definition of Done
- [ ] The analysis has taken place in exploration.ipynb
- [ ] All findings are well-documented.

**Comment by rhazn** [comment]
See #39
