### ISSUE TITLE
Traffic Prediction Based on Weather.

### ISSUE THREAD

**Issue by 123harshil** [jvalue/made-template#44]
For the further process i will collect the data and explore the data and ensure the data quality.

**Comment by 123harshil** [comment]
After the exploring the data we will do the data cleaning. We will remove some of the data which are not useful for our prediction and update some of the missing values which are useful for the insights.

**Comment by 123harshil** [comment]
Then we will make the insights from the data using the data visualization techniques with the help of bars and charts.

**Comment by rhazn** [comment]
Please work in your own repository fork, not in the template repository.
