### ISSUE TITLE
git issue testing

### ISSUE THREAD

**Issue by Ghulam-Rabbani-Azeem** [jvalue/made-template#52]
## User Story
1. As a {user/persona}
2. I want {to perform this action}
3. So that {I can accomplish this goal}

## User Acceptance Criteria
- [ ] {acceptance criteria 1}

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [x] All tests are passing
- [ ] Documentation is updated/extended

**Comment by rhazn** [comment]
Please work in your own repository, not in the template repository.
